//HTTP 메서드 연습

GET/search?q=hello&hl=koHTTP/1.1
Host:www.google.com

HTTP/1.1 200 OK
Content-type:application/json
Content-Length:34
{
 "username":"Json"
 "age":"32"
}

POST/memebers HTTP/1.1
Content-type:application/json
{
"username":"hello"
"age":"20"
}

