package hello.item;

public enum CoffeeOrigin {
    BRAZIL_SANTOS, COLOMBIA_SUPREMO, JAMAICA_BLUEMOUNTAIN, ETHIOPIA_YIRGACHEFFE, KENYA_AA,
    COSTARICA_TARRAZU, TANZANIA_KILIMANJARO, YEMEN_MOCCA, HAWAII_CONA, GUATEMALA_ANTIGUA, PANAMA_GEISHA, ELSALVADOR
}
